project:
  type: book

book:
  title: "Orientación Educativa en Contextos Sociales"
  subtitle: "Material docente para el Grado en Educación Social (UJA)"
  author:
    - name: "Samuel P. León"
      affiliation: "Dep. Pedagogía (MIDE). Universidad de Jaén"
  date: today
  language: es
  chapters:
    - index.qmd
    - prologo.qmd
    - part: "Unidad 1 · Fundamentos"
      chapters:
        - unidades/01-unidad1.qmd
    - part: "Unidad 2 · Modelos de orientación"
      chapters:
        - unidades/02-unidad2.qmd
    - part: "Unidad 3 · Diseño y aplicación"
      chapters:
        - unidades/03-unidad3.qmd
    - cierre.qmd
    
    - glosario.qmd
    
  sidebar:
    style: floating
    search: true
  page-navigation: true
  navbar:
    right:
      - icon: github
        href: https://github.com/Samigabacho/orientacion-educativa-libro
      - text: "Glosario"
        href: glosario.qmd

  favicon: fig/u2-modelos-cuadro.png

bibliography: referencias.bib
#csl: apa-spanish.csl 

website:
  site-url: https://samigabacho.github.io/orientacion-educativa-libro
  repo-url: https://github.com/Samigabacho/orientacion-educativa-libro

format:
  html:
    toc: true
    toc-depth: 3
    theme:
      light: cosmo
      dark: darkly
    css: estilos.scss
    number-sections: true
    code-fold: false
    link-citations: true

execute:
  freeze: auto
